# Generated by Django 4.1.2 on 2023-02-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.SmallIntegerField(null=True),
        ),
    ]
