# Generated by Django 4.1.2 on 2023-03-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_box_is_owner_remove_box_member'),
        ('authentication', '0003_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.box'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='box_owner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
