# Generated by Django 4.1.2 on 2023-02-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('code', models.CharField(max_length=20)),
                ('is_owner', models.BooleanField(default=False)),
                ('count', models.SmallIntegerField(default=1)),
                ('size', models.SmallIntegerField(validators=[game.validators.validate_box_size])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
