# Generated by Django 4.1.2 on 2023-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_box_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='code',
            field=models.SmallIntegerField(),
        ),
    ]
