# Generated by Django 4.1.2 on 2023-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_box_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='code',
            field=models.SmallIntegerField(null=True),
        ),
    ]
