# Generated by Django 4.1.2 on 2023-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_box_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='title',
            field=models.CharField(default='qwe', max_length=255),
            preserve_default=False,
        ),
    ]
