# Generated by Django 4.1.2 on 2023-03-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_box_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='box',
            name='member',
        ),
    ]
