# Generated by Django 4.1.2 on 2023-04-03 14:27

from django.db import migrations, models
import game.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_box_is_owner_remove_box_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='code',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.PositiveSmallIntegerField(validators=[game.validators.validate_box_size]),
        ),
    ]
