# Generated by Django 4.1.2 on 2023-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_box_code_alter_box_count_alter_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
