# Generated by Django 4.1.2 on 2023-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion
import game.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_box_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.PositiveSmallIntegerField(validators=[game.validators.validate_box_size], verbose_name='Количество игроков'),
        ),
        migrations.AlterField(
            model_name='box',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='PairUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.box')),
            ],
        ),
    ]
