# Generated by Django 4.1.2 on 2023-05-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_box_is_closed_alter_box_size_alter_box_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PairUser',
        ),
    ]
